spring:
  application:
    name: camunda
  datasource:
    url: jdbc:mysql://10.192.1.108:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&&serverTimezone=Asia/Shanghai
    username: root
    password: leapmotor&mydb.0314
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  servlet:
    context-path: /process
camunda:
  bpm:
    admin-user:
      id: luke
      password: 123456
      first-name: camunda
    filter:
      create: All tasks
