server:
  port: 8080
  servlet:
    context-path: /process
spring:
  application:
    name: camunda
  datasource:
    url: jdbc:mysql://10.192.1.108:3306/camunda?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&&serverTimezone=Asia/Shanghai
    username: root
    password: leapmotor&mydb.0314
    driver-class-name: com.mysql.jdbc.Driver

# https://docs.camunda.org/manual/latest/user-guide/spring-boot-integration/configuration/
camunda:
  bpm:
    admin-user:
      id: luke
      password: 123456
      first-name: camunda
    filter:
      create: All tasks
    webapp:
      index-redirect-enabled: true
    history-level: audit
    auto-deployment-enabled: false  # 禁止自动部署
    authorization:
      tenant-check-enabled: false
