server:
  shutdown: graceful

spring:
  output:
    ansi:
      enabled: always
  lifecycle:
    timeout-per-shutdown-phase: 120s

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown,health
      base-path: /sys/actuator
  server:
    port: 8180